export enum InvestmentsType {
  HOME = 'HOME',
  SUBSCRIPTION = 'SUBSCRIPTION',
  PROFESSIONAL = 'PROFESSIONAL',
  EDUCATION = 'EDUCATION',
  HEALTH_CARE = 'HEALTH_CARE',
  TRANSPORT = 'TRANSPORT',
  MARKET = 'MARKET',
  SHOPPING = 'SHOPPING',
  TRAVEL = 'TRAVEL',
  FOOD = 'FOOD',
  LEISURE = 'LEISURE',
  GAMES = 'GAMES',
  BOOKS = 'BOOKS',
  CLOTHES = 'CLOTHES',
  BILLS = 'BILLS',
  OTHERS = 'OTHERS'
}